### ISSUE TITLE
这个怎么办啊

### ISSUE THREAD

**Issue by ghost** [cssxsh/mirai-hibernate-plugin#19]
[arch2023-08-13.log](https://github.com/cssxsh/mirai-hibernate-http/files/12329053/arch2023-08-13.log)

**Comment by cssxsh** [comment]
这是你第二次乱发 issue 了

**Comment by cssxsh** [comment]
> 	at global-shared//xyz.cssxsh.mirai.hibernate.MiraiHibernatePlugin.onLoad(MiraiHibernatePlugin.kt:27)

请不要乱放插件
他应该放到 plugins
