### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by Xixi14** [cssxsh/mirai-hibernate-plugin#20]
> 2023-08-14 10:16:22 V/Bot.xx: Event: GroupRecall(bot=Bot(xx), authorId=xx, messageIds=[5848], messageInternalIds=[1765528725], messageTime=1691979378, operator=NormalMember(xx), group=Group(xx), author=NormalMember(xx))

> 2023-08-14 10:19:10 V/Bot.xx: Event: GroupRecall(bot=Bot(xx), authorId=xx, messageIds=[631223], messageInternalIds=[1737680860], messageTime=1691979545, operator=NormalMember(xx), group=Group(xx), author=NormalMember(xx))

> 2023-08-14 10:19:10 W/mirai-hibernate-plugin: No found origin message for GroupRecall(bot=Bot(xx), authorId=xx, messageIds=[631223], messageInternalIds=[1737680860], messageTime=1691979545, operator=NormalMember(xx), group=Group(xx), author=NormalMember(xx))
获取不到群消息记录，报错了

**Comment by Xixi14** [comment]
？为什么关掉了

**Comment by cssxsh** [comment]
因为符合预期
